# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import job_pb2 as job__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in job_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class JobStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCreateJobInfo = channel.unary_unary(
                '/PredictService.JobGrpcService.V1.Job/GetCreateJobInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=job__pb2.GetCreateJobInfoReply.FromString,
                _registered_method=True)
        self.CreateJob = channel.unary_unary(
                '/PredictService.JobGrpcService.V1.Job/CreateJob',
                request_serializer=job__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=job__pb2.CreateJobReply.FromString,
                _registered_method=True)
        self.CreateJobAndWait = channel.unary_unary(
                '/PredictService.JobGrpcService.V1.Job/CreateJobAndWait',
                request_serializer=job__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=job__pb2.JobStatus.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/PredictService.JobGrpcService.V1.Job/GetJobStatus',
                request_serializer=job__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=job__pb2.JobStatus.FromString,
                _registered_method=True)
        self.ClearJobResults = channel.unary_unary(
                '/PredictService.JobGrpcService.V1.Job/ClearJobResults',
                request_serializer=job__pb2.ClearJobResultsRequest.SerializeToString,
                response_deserializer=job__pb2.ClearJobResultsReply.FromString,
                _registered_method=True)
        self.GetJobOutput = channel.unary_unary(
                '/PredictService.JobGrpcService.V1.Job/GetJobOutput',
                request_serializer=job__pb2.GetJobOutputRequest.SerializeToString,
                response_deserializer=job__pb2.GetJobOutputReply.FromString,
                _registered_method=True)
        self.GetChildJobs = channel.unary_unary(
                '/PredictService.JobGrpcService.V1.Job/GetChildJobs',
                request_serializer=job__pb2.GetChildJobsRequest.SerializeToString,
                response_deserializer=job__pb2.GetChildJobsReply.FromString,
                _registered_method=True)
        self.CopyOutputDocuments = channel.unary_unary(
                '/PredictService.JobGrpcService.V1.Job/CopyOutputDocuments',
                request_serializer=job__pb2.CopyOutputDocumentsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ProcessDocumentsStream = channel.stream_stream(
                '/PredictService.JobGrpcService.V1.Job/ProcessDocumentsStream',
                request_serializer=job__pb2.InputDocument.SerializeToString,
                response_deserializer=job__pb2.OutputDocument.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/PredictService.JobGrpcService.V1.Job/CancelJob',
                request_serializer=job__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class JobServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCreateJobInfo(self, request, context):
        """Получить информацию для создания задачи
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateJob(self, request, context):
        """Создать задачу
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateJobAndWait(self, request, context):
        """Создать задачу, ожидать завершения задачи
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Получить статус задачи
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearJobResults(self, request, context):
        """Очистить результаты задачи
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobOutput(self, request, context):
        """Получить обработанные документы
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildJobs(self, request, context):
        """Получить список идентификаторов дочерних задач
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyOutputDocuments(self, request, context):
        """Копировать обработанные документы
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessDocumentsStream(self, request_iterator, context):
        """Выполнить потоковую обработку документов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Отменить (остановить) выполнение задачи
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCreateJobInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCreateJobInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=job__pb2.GetCreateJobInfoReply.SerializeToString,
            ),
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=job__pb2.CreateJobRequest.FromString,
                    response_serializer=job__pb2.CreateJobReply.SerializeToString,
            ),
            'CreateJobAndWait': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJobAndWait,
                    request_deserializer=job__pb2.CreateJobRequest.FromString,
                    response_serializer=job__pb2.JobStatus.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=job__pb2.GetJobStatusRequest.FromString,
                    response_serializer=job__pb2.JobStatus.SerializeToString,
            ),
            'ClearJobResults': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearJobResults,
                    request_deserializer=job__pb2.ClearJobResultsRequest.FromString,
                    response_serializer=job__pb2.ClearJobResultsReply.SerializeToString,
            ),
            'GetJobOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobOutput,
                    request_deserializer=job__pb2.GetJobOutputRequest.FromString,
                    response_serializer=job__pb2.GetJobOutputReply.SerializeToString,
            ),
            'GetChildJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChildJobs,
                    request_deserializer=job__pb2.GetChildJobsRequest.FromString,
                    response_serializer=job__pb2.GetChildJobsReply.SerializeToString,
            ),
            'CopyOutputDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyOutputDocuments,
                    request_deserializer=job__pb2.CopyOutputDocumentsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ProcessDocumentsStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ProcessDocumentsStream,
                    request_deserializer=job__pb2.InputDocument.FromString,
                    response_serializer=job__pb2.OutputDocument.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=job__pb2.CancelJobRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PredictService.JobGrpcService.V1.Job', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Job(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCreateJobInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictService.JobGrpcService.V1.Job/GetCreateJobInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            job__pb2.GetCreateJobInfoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictService.JobGrpcService.V1.Job/CreateJob',
            job__pb2.CreateJobRequest.SerializeToString,
            job__pb2.CreateJobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateJobAndWait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictService.JobGrpcService.V1.Job/CreateJobAndWait',
            job__pb2.CreateJobRequest.SerializeToString,
            job__pb2.JobStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictService.JobGrpcService.V1.Job/GetJobStatus',
            job__pb2.GetJobStatusRequest.SerializeToString,
            job__pb2.JobStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearJobResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictService.JobGrpcService.V1.Job/ClearJobResults',
            job__pb2.ClearJobResultsRequest.SerializeToString,
            job__pb2.ClearJobResultsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictService.JobGrpcService.V1.Job/GetJobOutput',
            job__pb2.GetJobOutputRequest.SerializeToString,
            job__pb2.GetJobOutputReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChildJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictService.JobGrpcService.V1.Job/GetChildJobs',
            job__pb2.GetChildJobsRequest.SerializeToString,
            job__pb2.GetChildJobsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyOutputDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictService.JobGrpcService.V1.Job/CopyOutputDocuments',
            job__pb2.CopyOutputDocumentsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessDocumentsStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/PredictService.JobGrpcService.V1.Job/ProcessDocumentsStream',
            job__pb2.InputDocument.SerializeToString,
            job__pb2.OutputDocument.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictService.JobGrpcService.V1.Job/CancelJob',
            job__pb2.CancelJobRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
